### ISSUE TITLE
同学您好

### ISSUE THREAD

**Issue by cdefgabguitar** [bukanyohandi/CSC1001#1]
请问您有csc1001的期末考试题吗？我愿意付费购买，麻烦您了！！！
我的QQ：540904099

**Comment by bukanyohandi** [comment]
我没有那个期末考题。 对不起！

**Comment by cdefgabguitar** [comment]
好的，谢啦。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年12月1日(周四) 下午5:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [bukanyohandi/CSC1001] 同学您好 (Issue #1)




 
我没有那个期末考题。 对不起！
